spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://10.122.49.55:15432/PROJ_DSCQM?useUnicode=true&characterEncoding=UTF-8
    username: proj_dscqm
    password: proj_dscqm
    driver-class-name: org.postgresql.Driver
dbType: greenplum
# 表空间
schema: dscqm_pcg
# 模板公共路径
templateFolderPath: D:\devil13th\github\com-thd-springboot-framework-parent\com-thd-springboot-framework-generator\src\main\resources\template\ssm\
#  生成文件公共路径
targetFolderPath: D:\deleteme\cg\
# 包配置
coding:
  servicePackageName: com.thd.springboot.framework.example.service
  mapperPackageName: com.thd.springboot.framework.example.mapper
  controllerPackageName: com.thd.springboot.framework.example.controller
  entityPackageName: com.thd.springboot.framework.example.entity
# 自定义的属性 - map类型

custom:
  map:
    name: codeGen
    version: 1.0
    a: 1
    b: 2
    c: 3
    d: 4





logging:
  config: classpath:logback-spring.xml
  path: D:/deleteme/logbacks

